
/*
 * 
 */

package es.sistra.clientcert.wsclient.afirma.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 03 16:07:14 CEST 2015
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "ValidacionService", 
                  wsdlLocation = "ValidarCertificado.wsdl",
                  targetNamespace = "http://afirmaws/services/ValidarCertificado") 
public class ValidacionService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://afirmaws/services/ValidarCertificado", "ValidacionService");
    public final static QName ValidarCertificado = new QName("http://afirmaws/services/ValidarCertificado", "ValidarCertificado");
    static {
        URL url = null;
        try {
            url = new URL("ValidarCertificado.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from ValidarCertificado.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ValidacionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidacionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ValidacionWS
     */
    @WebEndpoint(name = "ValidarCertificado")
    public ValidacionWS getValidarCertificado() {
        return super.getPort(ValidarCertificado, ValidacionWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidacionWS
     */
    @WebEndpoint(name = "ValidarCertificado")
    public ValidacionWS getValidarCertificado(WebServiceFeature... features) {
        return super.getPort(ValidarCertificado, ValidacionWS.class, features);
    }

}
