package es.sistra.clientcert.wsclient.afirma.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 03 16:07:14 CEST 2015
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://afirmaws/services/ValidarCertificado", name = "ValidacionWS")
@XmlSeeAlso({es.sistra.clientcert.wsclient.afirma.model.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ValidacionWS {

    @WebResult(name = "ValidarCertificadoReturn", targetNamespace = "http://afirmaws/services/ValidarCertificado", partName = "ValidarCertificadoReturn")
    @WebMethod(operationName = "ValidarCertificado")
    public java.lang.String validarCertificado(
        @WebParam(partName = "in0", name = "in0")
        java.lang.String in0
    );
}
