package es.apb.sistra.plugins.firma.ws.apbfirma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 21 14:30:57 CEST 2017
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "urn:es:apb:firma:ws:v1:firma", name = "FirmaWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FirmaWebService {

    @WebResult(name = "obtenerInfoCertificadoResponse", targetNamespace = "urn:es:apb:firma:ws:v1:firma", partName = "parameters")
    @WebMethod
    public ObtenerInfoCertificadoResponse obtenerInfoCertificado(
        @WebParam(partName = "parameters", name = "obtenerInfoCertificadoRequest", targetNamespace = "urn:es:apb:firma:ws:v1:firma")
        ObtenerInfoCertificadoRequest parameters
    ) throws WException;

    @WebResult(name = "firmarResponse", targetNamespace = "urn:es:apb:firma:ws:v1:firma", partName = "parameters")
    @WebMethod
    public FirmarResponse firmar(
        @WebParam(partName = "parameters", name = "firmarRequest", targetNamespace = "urn:es:apb:firma:ws:v1:firma")
        FirmarRequest parameters
    ) throws WException;

    @WebResult(name = "validarResponse", targetNamespace = "urn:es:apb:firma:ws:v1:firma", partName = "parameters")
    @WebMethod
    public ValidarResponse validar(
        @WebParam(partName = "parameters", name = "validarRequest", targetNamespace = "urn:es:apb:firma:ws:v1:firma")
        ValidarRequest parameters
    ) throws WException;
}
