
/*
 * 
 */

package es.apb.sistra.plugins.firma.ws.apbfirma;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 21 14:30:57 CEST 2017
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "FirmarService_v1_00", 
                  wsdlLocation = "FirmaService.wsdl",
                  targetNamespace = "urn:es:apb:firma:ws:v1:firma") 
public class FirmarServiceV100 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:es:apb:firma:ws:v1:firma", "FirmarService_v1_00");
    public final static QName FirmaWebServiceImplPort = new QName("urn:es:apb:firma:ws:v1:firma", "FirmaWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("FirmaService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from FirmaService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FirmarServiceV100(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FirmarServiceV100(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmarServiceV100() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns FirmaWebService
     */
    @WebEndpoint(name = "FirmaWebServiceImplPort")
    public FirmaWebService getFirmaWebServiceImplPort() {
        return super.getPort(FirmaWebServiceImplPort, FirmaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaWebService
     */
    @WebEndpoint(name = "FirmaWebServiceImplPort")
    public FirmaWebService getFirmaWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FirmaWebServiceImplPort, FirmaWebService.class, features);
    }

}
