
package es.apb.sistra.plugins.firma.ws.apbfirma;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 21 14:30:57 CEST 2017
 * Generated source version: 2.2.7
 * 
 */

@WebFault(name = "ExcepcionWS", targetNamespace = "urn:es:apb:firma:ws:v1:firma")
public class WException extends Exception {
    public static final long serialVersionUID = 20170921143057L;
    
    private es.apb.sistra.plugins.firma.ws.apbfirma.ExcepcionWS excepcionWS;

    public WException() {
        super();
    }
    
    public WException(String message) {
        super(message);
    }
    
    public WException(String message, Throwable cause) {
        super(message, cause);
    }

    public WException(String message, es.apb.sistra.plugins.firma.ws.apbfirma.ExcepcionWS excepcionWS) {
        super(message);
        this.excepcionWS = excepcionWS;
    }

    public WException(String message, es.apb.sistra.plugins.firma.ws.apbfirma.ExcepcionWS excepcionWS, Throwable cause) {
        super(message, cause);
        this.excepcionWS = excepcionWS;
    }

    public es.apb.sistra.plugins.firma.ws.apbfirma.ExcepcionWS getFaultInfo() {
        return this.excepcionWS;
    }
}
